---
title: "Uganda 2018-19"
author: "Andy Kim and Nolan Gunter"
output: pdf_document
---

```{r read libraries}
library(devtools)
library(EconomicClusters) #devtools::install_github("Lauren-Eyler/EconomicClusters")
library(haven)
library(weights)
library(parallelDist) #install.packages('parallelDist')
library(foreach)
library(doParallel)
library(survey)
library(Hmisc)
library(descr) #install.packages('descr')
library(tidyverse)
library(car)
library(stats)
```

```{r read data}
dataset <- read_dta("~/Dropbox/EconomicClusters/Uganda 2018-19/UGHR7IFL.DTA")
```

Next, we use the information from the DHS Wealth Index PCA data from: https://dhsprogram.com/topics/wealth-index/Wealth-Index-Construction.cfm

For this analysis, the cutoff value we chose to subset the data was 0.05. Other cutoff points are valid.

Pages 2-4 of this document detail how this PCA was run: https://dhsprogram.com/programming/wealth%20index/Steps_to_constructing_the_new_DHS_Wealth_Index.pdf

```{r}
pca <- readxl::read_xlsx("~/Dropbox/EconomicClusters/Uganda 2018-19/uganda_2019_pca.xlsx")
imp_pca <- pca %>% filter(PCA >= 0.03)
```

```{r}
dataset <- dataset %>% 
  mutate(setting=car::recode(as.numeric(hv025),
                          "1 = 'urban';
                          2 = 'rural';
                          else = NA",
                          as.factor = TRUE,
                          levels = c('urban', 'rural')),
         water=car::recode(as.numeric(hv201),
                          "11 = 'pipe_dwel';
                          12 = 'pipe_yard'; 
                          13 = 'pipe_neighbor'; 
                          14 = 'pipe_public'; 
                          c('20','21','30','31','32') = 'well';
                          c('41', '42', '43', '51') = 'surface';
                          c('61', '62', '71', '96') = 'other';
                          else = NA",
                          as.factor=TRUE,
                          levels=c('pipe_dwel', 'pipe_yard', 'pipe_neighbor', 
                                   'pipe_public', 'well', 'surface', 'other')),
         toilet=car::recode(as.numeric(hv205),
                          "c('10','11','12','13','14','15') = 'flush';
                          c('20', '21', '22', '23') = 'pitlat';
                          c('41', '42', '43', '96') = 'other';
                          31 = 'none';
                          else = NA",
                          as.factor=TRUE,
                          levels=c('flush', 'pitlat', 'none', 'other')),
         cookfuel=car::recode(as.numeric(hv226),
                          "1 = 'electricity';
                          2 = 'LPG'; 
                          3 = 'natural gas'; 
                          4 = 'biogas'; 
                          5 = 'kerosene';
                          6 = 'coal/lignite'; 
                          7 = 'charcoal'; 
                          8 = 'wood'; 
                          9 = 'straw/shrubs/grass'; 
                          10 = 'crop';
                          11 = 'dung'; 
                          95 = 'nofoodcookedinhouse'; 
                          96 = 'other';
                          else = NA",
                          as.factor=TRUE,
                          levels=c('electricity', 'LPG', 'natural gas', 
                                   'biogas', 'kerosene', 'coal/lignite', 'charcoal',
                                   'wood', 'straw/shrubs/grass', 'crop', 'dung',
                                   'nofoodcookedinhouse', 'other')),
         floor=car::recode(as.numeric(hv213),
                          "c('11','12') = 'natural';
                          c('21', '22') = 'rudimentary';
                          c('31', '32', '33', '34', '35') = 'finished';
                          96 = 'other';
                          else = NA",
                          as.factor=TRUE,
                          levels=c('natural', 'rudimentary', 'finished', 'other')),
         roof=car::recode(as.numeric(hv215),
                          "c('11','12', '13') = 'natural';
                          c('21', '22', '23', '24') = 'rudimentary';
                          c('31', '32', '33', '34', '35', '36') = 'finished';
                          96 = 'other';
                          else = NA",
                          as.factor=TRUE,
                          levels=c('natural', 'rudimentary', 'finished', 'other')),
         wall=car::recode(as.numeric(hv214),
                          "c('11','12', '13') = 'natural';
                          c('21', '22', '23', '24', '25', '26') = 'rudimentary';
                          c('31', '32', '33', '34', '35', '36') = 'finished';
                          96 = 'other';
                          else = NA",
                          as.factor=TRUE,
                          levels=c('natural', 'rudimentary', 'finished', 'other')),)
```

```{r}
data_full <- dataset %>% select(water, toilet, cookfuel, hv206, hv207, hv208, hv209, 
                                
                                hv212, hv213, hv214, hv243a, hv243b, hv243e, hv247, sh114g, sh114i, sh114k, sh114m, sh114n, sh114o, sh114p)

colnames(data_full)<-c("water", "toilet", "cooking fuel", "electricity", "radio", "television", "computer", "refrigerator", "dvd", "table", "sofa", "bed", "cupboard", "clock", "watch", "cell", "motorcycle", "cartruck", ""
                       
                       "cartruck", "floor", "wall", "cell", "watch", "computer", "bankaccount", "freezer", "washingmachine", "dvd", "bed", "table", "chair", "cabinet")
                    
```

